/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package maid.service.Maid;

import java.sql.*;
import java.util.*;
import javax.swing.JOptionPane;
import maid.service.DBConnect;
import maid.service.LoginFrame;

/**
 *
 * @author hasib
 */
public class MyAccount extends javax.swing.JFrame {

    private Connection con;
    private PreparedStatement pst;
 
    /**
     * Creates new form MyAccount
     */
    public MyAccount() {
        initComponents();
     con = DBConnect.ConncerDB();

        lbl_maid.setText(String.valueOf(MaidClass.Name).toString());
        lbl_name.setText(String.valueOf(MaidClass.Name).toString());
        lbl_nid.setText(String.valueOf(MaidClass.id).toString());
        lbl_password.setText(String.valueOf(MaidClass.password).toString());
        lbl_worktype.setText(String.valueOf(MaidClass.worktype).toString());
        lbl_location.setText(String.valueOf(MaidClass.location).toString());
        lbl_holiday.setText(String.valueOf(MaidClass.holiday).toString());
        lbl_question.setText(String.valueOf(MaidClass.question).toString());
        lbl_answer.setText(String.valueOf(MaidClass.answer).toString());
        lbl_gender.setText(String.valueOf(MaidClass.gender).toString());
        lbl_salary.setText(String.valueOf(MaidClass.salary).toString());
        lbl_workinghours.setText(String.valueOf(MaidClass.workinghours).toString());
        lbl_phonenumber.setText(String.valueOf(MaidClass.phonenumber).toString());
        Calender();
    }

    public void Calender() {
        Calendar cal = new GregorianCalendar();
        int month = cal.get(Calendar.MONTH);
        int year = cal.get(Calendar.YEAR);
        int day = cal.get(Calendar.DAY_OF_MONTH);
        datefield.setText(+day + "-" + (month + 1 ) + "-" + year);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        homebutton1 = new javax.swing.JButton();
        contactus1 = new javax.swing.JButton();
        logoutbutton = new javax.swing.JButton();
        whatweofferbutton1 = new javax.swing.JButton();
        whyusbutton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lbl_maid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        datefield = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lbl_nid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lbl_name = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lbl_password = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lbl_worktype = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        lbl_location = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        lbl_holiday = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        lbl_question = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        lbl_answer = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        lbl_gender = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        lbl_salary = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        lbl_workinghours = new javax.swing.JTextField();
        savebutton = new javax.swing.JButton();
        editbutton = new javax.swing.JButton();
        lbl_phonenumber = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));

        jPanel3.setBackground(new java.awt.Color(0, 204, 255));

        homebutton1.setBackground(new java.awt.Color(0, 204, 255));
        homebutton1.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        homebutton1.setText("Home");
        homebutton1.setBorder(new javax.swing.border.MatteBorder(null));
        homebutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebutton1ActionPerformed(evt);
            }
        });

        contactus1.setBackground(new java.awt.Color(0, 204, 255));
        contactus1.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        contactus1.setText("Contact us");
        contactus1.setBorder(new javax.swing.border.MatteBorder(null));
        contactus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactus1ActionPerformed(evt);
            }
        });

        logoutbutton.setBackground(new java.awt.Color(0, 204, 255));
        logoutbutton.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        logoutbutton.setText("Logout");
        logoutbutton.setBorder(new javax.swing.border.MatteBorder(null));
        logoutbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbuttonActionPerformed(evt);
            }
        });

        whatweofferbutton1.setBackground(new java.awt.Color(0, 204, 255));
        whatweofferbutton1.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        whatweofferbutton1.setText("What we offer");
        whatweofferbutton1.setBorder(new javax.swing.border.MatteBorder(null));
        whatweofferbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                whatweofferbutton1ActionPerformed(evt);
            }
        });

        whyusbutton1.setBackground(new java.awt.Color(0, 204, 255));
        whyusbutton1.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        whyusbutton1.setText("Why us");
        whyusbutton1.setBorder(new javax.swing.border.MatteBorder(null));
        whyusbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                whyusbutton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(homebutton1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(whatweofferbutton1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(whyusbutton1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(contactus1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 817, Short.MAX_VALUE)
                .addComponent(logoutbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(whatweofferbutton1)
                        .addComponent(whyusbutton1)
                        .addComponent(contactus1))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(homebutton1)
                        .addComponent(logoutbutton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel1.setText("Date :");

        lbl_maid.setEditable(false);
        lbl_maid.setBackground(new java.awt.Color(0, 255, 255));
        lbl_maid.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lbl_maid.setBorder(null);
        lbl_maid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl_maidActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel2.setText("User :");

        datefield.setEditable(false);
        datefield.setBackground(new java.awt.Color(0, 255, 255));
        datefield.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        datefield.setBorder(null);

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel3.setText("NID :");

        lbl_nid.setEditable(false);
        lbl_nid.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel4.setText("Name :");

        lbl_name.setEditable(false);
        lbl_name.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel5.setText("Password :");

        lbl_password.setEditable(false);
        lbl_password.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel6.setText("Work type :");

        lbl_worktype.setEditable(false);
        lbl_worktype.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel7.setText("Location :");

        lbl_location.setEditable(false);
        lbl_location.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel8.setText("Holiday :");

        lbl_holiday.setEditable(false);
        lbl_holiday.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel9.setText("Question :");

        lbl_question.setEditable(false);
        lbl_question.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel10.setText("Answer :");

        lbl_answer.setEditable(false);
        lbl_answer.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel11.setText("Gender :");

        lbl_gender.setEditable(false);
        lbl_gender.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel12.setText("Salary :");

        lbl_salary.setEditable(false);
        lbl_salary.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel13.setText("Working Hours :");

        lbl_workinghours.setEditable(false);
        lbl_workinghours.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        savebutton.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        savebutton.setText("Save");
        savebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebuttonActionPerformed(evt);
            }
        });

        editbutton.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        editbutton.setText("Edit");
        editbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editbuttonActionPerformed(evt);
            }
        });

        lbl_phonenumber.setEditable(false);
        lbl_phonenumber.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel14.setText("Phone :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_maid, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(datefield))
                .addGap(255, 255, 255))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(62, 62, 62)
                                .addComponent(lbl_nid, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbl_name, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                                    .addComponent(lbl_password)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(46, 46, 46)
                                .addComponent(lbl_salary)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(177, 177, 177)
                                .addComponent(savebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(editbutton))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(372, 372, 372)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbl_phonenumber, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(18, 18, 18)
                                        .addComponent(lbl_workinghours, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_worktype, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                            .addComponent(lbl_location)
                            .addComponent(lbl_holiday)
                            .addComponent(lbl_question)
                            .addComponent(lbl_answer)
                            .addComponent(lbl_gender))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(872, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(433, 433, 433)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(lbl_maid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(datefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(91, 91, 91)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbl_nid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(lbl_workinghours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(lbl_phonenumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(lbl_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lbl_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lbl_worktype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lbl_location, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lbl_holiday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lbl_question, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lbl_answer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lbl_gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lbl_salary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(savebutton)
                    .addComponent(editbutton))
                .addGap(0, 99, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(71, 71, 71)
                    .addComponent(jLabel2)
                    .addContainerGap(645, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homebutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebutton1ActionPerformed
        // TODO add your handling code here:
        LoginMaid lg = new LoginMaid();
        lg.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_homebutton1ActionPerformed

    private void contactus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactus1ActionPerformed
        // TODO add your handling code here:
        ContactUsFrame cf = new ContactUsFrame();
        cf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_contactus1ActionPerformed

    private void whatweofferbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_whatweofferbutton1ActionPerformed
        // TODO add your handling code here:
        WhatWeOfferFrame wf = new WhatWeOfferFrame();
        wf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_whatweofferbutton1ActionPerformed

    private void whyusbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_whyusbutton1ActionPerformed
        // TODO add your handling code here:
        WhyUsFrame wf = new WhyUsFrame();
        wf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_whyusbutton1ActionPerformed

    private void lbl_maidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl_maidActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_lbl_maidActionPerformed

    private void savebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebuttonActionPerformed
        // TODO add your handling code here:

        try {
            String value1 = lbl_name.getText();
            String value2 = lbl_password.getText();
            String value3 = lbl_worktype.getText();
            String value4 = lbl_location.getText();
            String value5 = lbl_holiday.getText();
            String value6 = lbl_question.getText();
            String value7 = lbl_answer.getText();
            String value8 = lbl_salary.getText();
            String value9 = lbl_workinghours.getText();
            String value10 = lbl_phonenumber.getText();

            String sql = "Update `maid frame` set `Name`='" + value1 + "',`Password`='" + value2 + "',`Work type` ='" + value3 + "',`Location`='" + value4 + "',`Holiday`='" + value5 + "',`Question`='" + value6 + "',`Answer`='" + value7 + "',`Salary`='" + value8 + "', `Working Hours`='" + value9 + "',`Phone`='" + value10 + "' where `Nid`  = '" + lbl_nid.getText() + "'";
            pst = con.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Profile Update");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }
    }//GEN-LAST:event_savebuttonActionPerformed

    private void editbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editbuttonActionPerformed
        // TODO add your handling code here:
        lbl_name.setEditable(true);
        lbl_password.setEditable(true);
        lbl_answer.setEditable(true);
        lbl_workinghours.setEditable(true);
        lbl_phonenumber.setEditable(true);
        lbl_salary.setEditable(true);
        lbl_question.setEditable(true);
        lbl_location.setEditable(true);
        lbl_worktype.setEditable(true);
        lbl_holiday.setEditable(true);
    }//GEN-LAST:event_editbuttonActionPerformed

    private void logoutbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbuttonActionPerformed
        // TODO add your handling code here:
        LoginFrame lf = new LoginFrame();
        lf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logoutbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton contactus1;
    private javax.swing.JTextField datefield;
    private javax.swing.JButton editbutton;
    private javax.swing.JButton homebutton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField lbl_answer;
    private javax.swing.JTextField lbl_gender;
    private javax.swing.JTextField lbl_holiday;
    private javax.swing.JTextField lbl_location;
    private javax.swing.JTextField lbl_maid;
    private javax.swing.JTextField lbl_name;
    private javax.swing.JTextField lbl_nid;
    private javax.swing.JTextField lbl_password;
    private javax.swing.JTextField lbl_phonenumber;
    private javax.swing.JTextField lbl_question;
    private javax.swing.JTextField lbl_salary;
    private javax.swing.JTextField lbl_workinghours;
    private javax.swing.JTextField lbl_worktype;
    private javax.swing.JButton logoutbutton;
    private javax.swing.JButton savebutton;
    private javax.swing.JButton whatweofferbutton1;
    private javax.swing.JButton whyusbutton1;
    // End of variables declaration//GEN-END:variables
}
