/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package maid.service;

import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import maid.service.Admin.AdminClass;
import maid.service.Admin.AdminFrame;
import maid.service.Maid.LoginMaid;
import maid.service.Maid.MaidClass;
import maid.service.User.LoginUser;
import maid.service.User.UserClass;

/**
 *
 *
 * @author hasib
 */
public class LoginFrame extends javax.swing.JFrame {

    String k;
    private Connection con;
    private Statement st;
    private ResultSet rs;

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        whatweofferbutton = new javax.swing.JButton();
        homebuttonregisterframe = new javax.swing.JButton();
        whyusbutton = new javax.swing.JButton();
        contactus = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nidfield = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        passwordfield = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        signinbutton = new javax.swing.JButton();
        forgotpasswordbutton = new javax.swing.JButton();
        registerbutton = new javax.swing.JButton();
        userbutton = new javax.swing.JToggleButton();
        maidbutton = new javax.swing.JToggleButton();
        jLabel8 = new javax.swing.JLabel();
        adminbutton = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        loginbutton = new javax.swing.JButton();
        registerbutton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(0, 255, 255));

        jPanel3.setBackground(new java.awt.Color(0, 204, 255));

        whatweofferbutton.setBackground(new java.awt.Color(0, 204, 255));
        whatweofferbutton.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        whatweofferbutton.setText("What we offer");
        whatweofferbutton.setBorder(new javax.swing.border.MatteBorder(null));
        whatweofferbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                whatweofferbuttonActionPerformed(evt);
            }
        });

        homebuttonregisterframe.setBackground(new java.awt.Color(0, 204, 255));
        homebuttonregisterframe.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        homebuttonregisterframe.setText("Home");
        homebuttonregisterframe.setBorder(new javax.swing.border.MatteBorder(null));
        homebuttonregisterframe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebuttonregisterframeActionPerformed(evt);
            }
        });

        whyusbutton.setBackground(new java.awt.Color(0, 204, 255));
        whyusbutton.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        whyusbutton.setText("Why us");
        whyusbutton.setBorder(new javax.swing.border.MatteBorder(null));
        whyusbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                whyusbuttonActionPerformed(evt);
            }
        });

        contactus.setBackground(new java.awt.Color(0, 204, 255));
        contactus.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        contactus.setText("Contact us");
        contactus.setBorder(new javax.swing.border.MatteBorder(null));
        contactus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(homebuttonregisterframe, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(whatweofferbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(whyusbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(contactus, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(homebuttonregisterframe)
                    .addComponent(whatweofferbutton)
                    .addComponent(whyusbutton)
                    .addComponent(contactus))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel4.setBackground(new java.awt.Color(0, 204, 255));

        jLabel1.setBackground(new java.awt.Color(0, 204, 255));
        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Login");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(300, 300, 300))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Nid Number");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Password");

        jLabel4.setText("Forgot Password ?");

        jLabel6.setText("Don't have an account yet?");

        signinbutton.setBackground(new java.awt.Color(102, 255, 102));
        signinbutton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        signinbutton.setText("Sign in");
        signinbutton.setActionCommand("loginbutton");
        signinbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinbuttonActionPerformed(evt);
            }
        });

        forgotpasswordbutton.setForeground(new java.awt.Color(0, 0, 255));
        forgotpasswordbutton.setText("click here");
        forgotpasswordbutton.setBorder(new javax.swing.border.MatteBorder(null));
        forgotpasswordbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgotpasswordbuttonActionPerformed(evt);
            }
        });

        registerbutton.setForeground(new java.awt.Color(0, 0, 255));
        registerbutton.setText("Register now");
        registerbutton.setActionCommand("registernowbutton");
        registerbutton.setBorder(new javax.swing.border.MatteBorder(null));
        registerbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerbuttonActionPerformed(evt);
            }
        });

        buttonGroup1.add(userbutton);
        userbutton.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        userbutton.setText("User");
        userbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userbuttonMouseClicked(evt);
            }
        });
        userbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userbuttonActionPerformed(evt);
            }
        });

        buttonGroup1.add(maidbutton);
        maidbutton.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        maidbutton.setText("Maid");
        maidbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maidbuttonMouseClicked(evt);
            }
        });
        maidbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maidbuttonActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel8.setText("OR");

        buttonGroup1.add(adminbutton);
        adminbutton.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        adminbutton.setText("Admin");
        adminbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminbuttonMouseClicked(evt);
            }
        });
        adminbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(forgotpasswordbutton)
                        .addGap(262, 262, 262))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(registerbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(233, 233, 233))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(281, 281, 281))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(userbutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 180, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(signinbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(passwordfield, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nidfield, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(190, 190, 190))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jLabel8)
                .addGap(33, 33, 33)
                .addComponent(maidbutton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(adminbutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(294, 294, 294))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jLabel2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(nidfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(maidbutton))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(userbutton)
                                .addComponent(jLabel8)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(adminbutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(passwordfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(forgotpasswordbutton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(registerbutton))
                .addGap(28, 28, 28)
                .addComponent(signinbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Viner Hand ITC", 3, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 0));
        jLabel5.setText("Service");

        jLabel7.setFont(new java.awt.Font("Viner Hand ITC", 3, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setText("Maid");

        jLabel11.setFont(new java.awt.Font("PMingLiU-ExtB", 2, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 0, 204));
        jLabel11.setText("The new way to hire a trusted maid");

        loginbutton.setBackground(new java.awt.Color(102, 255, 102));
        loginbutton.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        loginbutton.setText("Login");
        loginbutton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        loginbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbuttonActionPerformed(evt);
            }
        });

        registerbutton1.setBackground(new java.awt.Color(102, 255, 102));
        registerbutton1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        registerbutton1.setText("Register");
        registerbutton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        registerbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerbutton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(loginbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(registerbutton1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(364, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(registerbutton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(loginbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addGap(32, 32, 32)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void forgotpasswordbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgotpasswordbuttonActionPerformed
        // TODO add your handling code here:
        String command = evt.getActionCommand();
        if (command.equals(forgotpasswordbutton.getText())) {
            ForgotPasswordFrame ff = new ForgotPasswordFrame();
            ff.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_forgotpasswordbuttonActionPerformed

    private void registerbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerbuttonActionPerformed
        // TODO add your handling code here:
        RegisterFrame rf = new RegisterFrame();
        rf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_registerbuttonActionPerformed

    private void signinbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinbuttonActionPerformed
        // TODO add your handling code here:

        try {
            Class.forName("com.mysql.jdbc.Driver");
            //Step-1: get a connection to the db
            con = DriverManager.getConnection("jdbc:mysql://localhost/maid service", "root", "");
            System.out.println("DB Connect Successful");
            //Step-2: create a statement
            st = con.createStatement();
        } catch (Exception e) {
            System.out.println("Error: " + e);
            e.printStackTrace();
        }
        if (con == null) {
            JOptionPane.showMessageDialog(this, "Connection Failed");
        } else {
            //user frame
            String sql = "SELECT * FROM `user frame`  where Nid = '" + nidfield.getText() + "'and Password ='" + passwordfield.getText() + "'";
            //maid frame
            String sqll = "SELECT * FROM `maid frame`  where Nid = '" + nidfield.getText() + "'and Password ='" + passwordfield.getText() + "'";
            //admin frame
            String sqlll = "SELECT * FROM `admin frame`  where Nid = '" + nidfield.getText() + "'and Password ='" + passwordfield.getText() + "'";
            if (null == k) {
                JOptionPane.showMessageDialog(this, "Select user or maid or admin");
            } else {
                switch (k) {
                    //User frame
                    case "User":
                        try {
                            Statement st = con.createStatement();
                            ResultSet rs = st.executeQuery(sql);
                            if (rs.next()) {
                                System.out.println("User");
                                LoginUser lu = new LoginUser();
                                lu.setVisible(true);
                                this.setVisible(false);

                                //user show information in my account page
                                String name = rs.getString(2);
                                UserClass.Name = name;

                                int id = rs.getInt(1);
                                UserClass.id = id;

                                String password = rs.getString(3);
                                UserClass.password = password;

                                String email = rs.getString(4);
                                UserClass.email = email;

                                String address = rs.getString(5);
                                UserClass.address = address;

                                String company = rs.getString(6);
                                UserClass.company = company;

                                String question = rs.getString(7);
                                UserClass.question = question;

                                String answer = rs.getString(8);
                                UserClass.answer = answer;

                                String gender = rs.getString(9);
                                UserClass.gender = gender;

                                String phonenumber = rs.getString(10);
                                UserClass.phonenumber = phonenumber;

                            } else {
                                JOptionPane.showMessageDialog(this, "Nid or Password is wrong");
                            }
                        } catch (SQLException ex) {
                            JOptionPane.showMessageDialog(this, ex);
                        }
                        break;
                    //Maid Frame
                    case "Maid":
                        try {
                            Statement st = con.createStatement();
                            ResultSet rs = st.executeQuery(sqll);
                            if (rs.next()) {
                                System.out.println("Maid");
                                LoginMaid lm = new LoginMaid();
                                lm.setVisible(true);
                                this.setVisible(false);

                                //maid show information in my account page
                                String name = rs.getString(2);
                                MaidClass.Name = name;

                                int id = rs.getInt(1);
                                MaidClass.id = id;

                                String password = rs.getString(3);
                                MaidClass.password = password;

                                String worktype = rs.getString(4);
                                MaidClass.worktype = worktype;

                                String location = rs.getString(5);
                                MaidClass.location = location;

                                String holiday = rs.getString(6);
                                MaidClass.holiday = holiday;

                                String question = rs.getString(7);
                                MaidClass.question = question;
                                String answer = rs.getString(8);
                                MaidClass.answer = answer;

                                String gender = rs.getString(9);
                                MaidClass.gender = gender;

                                String salary = rs.getString(10);
                                MaidClass.salary = salary;

                                String workinghours = rs.getString(11);
                                MaidClass.workinghours = workinghours;

                                String phonenumber = rs.getString(12);
                                MaidClass.phonenumber = phonenumber;

                            } else {
                                JOptionPane.showMessageDialog(this, "Nid or Password is wrong");
                            }
                        } catch (SQLException ex) {
                            JOptionPane.showMessageDialog(this, ex);
                        }
                        break;
                    //Admin frame
                    case "Admin":
                        try {
                            Statement st = con.createStatement();
                            ResultSet rs = st.executeQuery(sqlll);
                            if (rs.next()) {
                                System.out.println("Admin");
                                AdminFrame af = new AdminFrame();
                                af.setVisible(true);
                                this.setVisible(false);
                                String name = rs.getString(2);
                                AdminClass.Name = name;
                                int nid = rs.getInt(1);
                                AdminClass.id = nid;
                                String company = rs.getString(4);
                                AdminClass.company = company;
                                String password = rs.getString(3);
                                AdminClass.password = password;

                            } else {
                                JOptionPane.showMessageDialog(this, "Nid or Password is wrong");
                            }
                        } catch (SQLException ex) {
                            JOptionPane.showMessageDialog(this, ex);
                        }

                        break;
                    default:
                        break;
                }
            }
        }
    }//GEN-LAST:event_signinbuttonActionPerformed

    private void whatweofferbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_whatweofferbuttonActionPerformed
        // TODO add your handling code here:
        WhatWeOfferFrame wf = new WhatWeOfferFrame();
        wf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_whatweofferbuttonActionPerformed

    private void homebuttonregisterframeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebuttonregisterframeActionPerformed
        // TODO add your handling code here:

        HomePage hp = new HomePage();
        hp.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_homebuttonregisterframeActionPerformed

    private void whyusbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_whyusbuttonActionPerformed
        // TODO add your handling code here:
        WhyUsFrame wf = new WhyUsFrame();
        wf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_whyusbuttonActionPerformed

    private void loginbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbuttonActionPerformed
        // TODO add your handling code here:

        LoginFrame logf = new LoginFrame();
        logf.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_loginbuttonActionPerformed

    private void registerbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerbutton1ActionPerformed
        // TODO add your handling code here:

        RegisterFrame regf = new RegisterFrame();
        regf.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_registerbutton1ActionPerformed

    private void contactusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactusActionPerformed
        // TODO add your handling code here:
        ContactUsFrame cf = new ContactUsFrame();
        cf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_contactusActionPerformed

    private void userbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userbuttonActionPerformed
        // TODO add your handling code here:
        userbutton.setText("User");
        k = userbutton.getText();
        System.out.println(k);
    }//GEN-LAST:event_userbuttonActionPerformed

    private void userbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userbuttonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_userbuttonMouseClicked

    private void maidbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maidbuttonActionPerformed
        // TODO add your handling code here:
        maidbutton.setText("Maid");
        k = maidbutton.getText();
        System.out.println(k);
    }//GEN-LAST:event_maidbuttonActionPerformed

    private void maidbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maidbuttonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_maidbuttonMouseClicked

    private void adminbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminbuttonActionPerformed
        // TODO add your handling code here:
        adminbutton.setText("Admin");
        k = adminbutton.getText();
        System.out.println(k);

    }//GEN-LAST:event_adminbuttonActionPerformed

    private void adminbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminbuttonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_adminbuttonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton adminbutton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton contactus;
    private javax.swing.JButton forgotpasswordbutton;
    private javax.swing.JButton homebuttonregisterframe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton loginbutton;
    private javax.swing.JToggleButton maidbutton;
    private javax.swing.JTextField nidfield;
    private javax.swing.JPasswordField passwordfield;
    private javax.swing.JButton registerbutton;
    private javax.swing.JButton registerbutton1;
    private javax.swing.JButton signinbutton;
    private javax.swing.JToggleButton userbutton;
    private javax.swing.JButton whatweofferbutton;
    private javax.swing.JButton whyusbutton;
    // End of variables declaration//GEN-END:variables
}
