/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package maid.service;

import maid.service.Maid.MaidFrame;
import maid.service.User.UserFrame;



/**
 *
 * @author hasib
 */
public class RegisterFrame extends javax.swing.JFrame {

    /**
     * Creates new form RegisterFrome
     */
    public RegisterFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        maidbutton = new javax.swing.JButton();
        userbutton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        homebuttonregisterframe = new javax.swing.JButton();
        whyusbutton = new javax.swing.JButton();
        whatweofferbutton = new javax.swing.JButton();
        contactus = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));

        maidbutton.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        maidbutton.setText("Maid");
        maidbutton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        maidbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maidbuttonActionPerformed(evt);
            }
        });

        userbutton.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        userbutton.setText("User");
        userbutton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        userbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userbuttonActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 204, 255));

        homebuttonregisterframe.setBackground(new java.awt.Color(0, 204, 255));
        homebuttonregisterframe.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        homebuttonregisterframe.setText("Home");
        homebuttonregisterframe.setBorder(new javax.swing.border.MatteBorder(null));
        homebuttonregisterframe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebuttonregisterframeActionPerformed(evt);
            }
        });

        whyusbutton.setBackground(new java.awt.Color(0, 204, 255));
        whyusbutton.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        whyusbutton.setText("Why us");
        whyusbutton.setBorder(new javax.swing.border.MatteBorder(null));
        whyusbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                whyusbuttonActionPerformed(evt);
            }
        });

        whatweofferbutton.setBackground(new java.awt.Color(0, 204, 255));
        whatweofferbutton.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        whatweofferbutton.setText("What we offer");
        whatweofferbutton.setBorder(new javax.swing.border.MatteBorder(null));
        whatweofferbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                whatweofferbuttonActionPerformed(evt);
            }
        });

        contactus.setBackground(new java.awt.Color(0, 204, 255));
        contactus.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        contactus.setText("Contact us");
        contactus.setBorder(new javax.swing.border.MatteBorder(null));
        contactus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(homebuttonregisterframe, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(whatweofferbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(whyusbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(contactus, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(homebuttonregisterframe)
                    .addComponent(whatweofferbutton)
                    .addComponent(whyusbutton)
                    .addComponent(contactus))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel1.setText("where to register?");

        jLabel5.setFont(new java.awt.Font("Viner Hand ITC", 3, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 0));
        jLabel5.setText("Service");

        jLabel3.setFont(new java.awt.Font("Viner Hand ITC", 3, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Maid");

        jLabel2.setFont(new java.awt.Font("PMingLiU-ExtB", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 204));
        jLabel2.setText("The new way to hire a trusted maid");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(524, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(maidbutton)
                            .addComponent(userbutton)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(461, 461, 461))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(202, 202, 202)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(43, 43, 43)
                .addComponent(userbutton)
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addComponent(maidbutton)
                .addContainerGap(246, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homebuttonregisterframeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebuttonregisterframeActionPerformed
        // TODO add your handling code here:
        String command = evt.getActionCommand();
        if (command.equals(homebuttonregisterframe.getText())) {
            HomePage hp = new HomePage();
            hp.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_homebuttonregisterframeActionPerformed

    private void userbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userbuttonActionPerformed
        // TODO add your handling code here:
        String command = evt.getActionCommand();
        if(command.equals(userbutton.getText())){
            UserFrame use = new UserFrame();
            use.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_userbuttonActionPerformed

    private void maidbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maidbuttonActionPerformed
        // TODO add your handling code here:
        String command=evt.getActionCommand();
        if(command.equals(maidbutton.getText())){
            MaidFrame maid = new MaidFrame();
            maid.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_maidbuttonActionPerformed

    private void whyusbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_whyusbuttonActionPerformed
        // TODO add your handling code here:
        WhyUsFrame wf = new WhyUsFrame();
        wf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_whyusbuttonActionPerformed

    private void whatweofferbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_whatweofferbuttonActionPerformed
        // TODO add your handling code here:
        WhatWeOfferFrame wf = new WhatWeOfferFrame();
        wf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_whatweofferbuttonActionPerformed

    private void contactusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactusActionPerformed
        // TODO add your handling code here:
        ContactUsFrame cf = new ContactUsFrame();
        cf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_contactusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton contactus;
    private javax.swing.JButton homebuttonregisterframe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton maidbutton;
    private javax.swing.JButton userbutton;
    private javax.swing.JButton whatweofferbutton;
    private javax.swing.JButton whyusbutton;
    // End of variables declaration//GEN-END:variables
}
